# Generated by Django 4.1.6 on 2023-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_changer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
