# Generated by Django 4.1.6 on 2023-02-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_alter_changer_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='changer_bank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
