# Generated by Django 4.1.6 on 2023-02-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_alter_request_changer_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='currency_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bot_app.currencypair'),
        ),
    ]
