# Generated by Django 4.1.6 on 2023-02-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='customer_bank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
