# Generated by Django 4.1.6 on 2023-02-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_request_customer_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='bot_app.changer'),
        ),
    ]
