# Generated by Django 4.1.6 on 2023-02-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_alter_bankaccount_bank_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestModel',
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='ResponseModel',
        ),
    ]
