# Generated by Django 4.1.6 on 2023-02-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_rename_request_requestmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='Sbrigo', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
