# Generated by Django 4.1.6 on 2023-02-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_remove_bankaccount_bank_bankaccount_name_delete_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='choise_id',
            new_name='choice_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='changer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency_pair',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='response_id',
        ),
    ]
