# Generated by Django 4.1.6 on 2023-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_rename_choise_id_transaction_choice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerchoice',
            name='changer_bank_account',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerchoice',
            name='customer_bank_account',
            field=models.IntegerField(blank=True),
        ),
    ]
