# Generated by Django 4.1.6 on 2023-02-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_alter_customerchoice_changer_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='changer_accept_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_accept_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_send_money_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
