# Generated by Django 4.1.6 on 2023-02-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_alter_transaction_changer_accept_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='changer_accept_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_accept_date',
            field=models.DateTimeField(null=True),
        ),
    ]
