# Generated by Django 4.1.6 on 2023-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_alter_transaction_changer_accept_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='changer_proof',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_proof',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
