# Generated by Django 4.1.6 on 2023-02-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0018_alter_transaction_choice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchoice',
            name='changer_bank',
            field=models.CharField(default='sbr', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerchoice',
            name='customer_bank',
            field=models.CharField(default='sbr', max_length=50),
            preserve_default=False,
        ),
    ]
