# Generated by Django 4.1.6 on 2023-02-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0019_customerchoice_changer_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerchoice',
            name='customer_bank_account',
            field=models.IntegerField(null=True),
        ),
    ]
