# Generated by Django 4.1.7 on 2023-04-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('tg', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('lastName', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Changer',
            fields=[
                ('tg', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
            },
        ),
        migrations.CreateModel(
            name='ChangerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('bankAccount', models.IntegerField(unique=True, verbose_name='Номер счета')),
                ('isActive', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='db_model.changer', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Банковский счет обменника',
                'verbose_name_plural': 'Банковские счета обменников',
            },
        ),
        migrations.CreateModel(
            name='ChangerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerName', models.CharField(max_length=64, verbose_name='Название оффера')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('rate', models.FloatField(verbose_name='Курс в MNT')),
                ('minAmount', models.FloatField(blank=True, verbose_name='Минимальная сумма сделки')),
                ('maxAmount', models.FloatField(blank=True, verbose_name='Макимальная сумма сделки')),
                ('dateCreated', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('isActive', models.BooleanField(default=False)),
                ('banks', models.ManyToManyField(to='db_model.changerbankaccount', verbose_name='Банки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.changer', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('bankAccount', models.IntegerField(unique=True, verbose_name='Номер счета')),
                ('isActive', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='db_model.botuser', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Банковский счет пользователя',
                'verbose_name_plural': 'Банковские счета пользователей',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellCurrency', models.CharField(max_length=10)),
                ('buyCurrency', models.CharField(max_length=10)),
                ('sellAmount', models.FloatField()),
                ('buyAmount', models.FloatField()),
                ('rate', models.FloatField()),
                ('userSendMoneyDate', models.DateTimeField(blank=True)),
                ('userAcceptDate', models.DateTimeField(blank=True)),
                ('changerSendMoneyDate', models.DateTimeField(blank=True)),
                ('changerAcceptDate', models.DateTimeField(blank=True)),
                ('userProof', models.CharField(blank=True, max_length=100)),
                ('changerProof', models.CharField(blank=True, max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.changer')),
                ('changerBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.changerbankaccount')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.changeroffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.botuser')),
                ('userBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.userbankaccount')),
            ],
            options={
                'verbose_name': 'Совершенный перевод',
                'verbose_name_plural': 'Совершенные переводы',
            },
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('userAmount', models.FloatField()),
                ('userRate', models.FloatField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('sellBank', models.CharField(max_length=50)),
                ('buyBank', models.CharField(max_length=50)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.changer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.changeroffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.botuser')),
            ],
            options={
                'verbose_name': 'Отклик на оффер',
                'verbose_name_plural': 'Отклики на офферы',
            },
        ),
    ]
