# Generated by Django 4.1.7 on 2023-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeroffer',
            name='maxAmount',
            field=models.FloatField(blank=True, null=True, verbose_name='Макимальная сумма сделки'),
        ),
        migrations.AlterField(
            model_name='changeroffer',
            name='minAmount',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальная сумма сделки'),
        ),
    ]
