# Generated by Django 4.2 on 2023-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0002_alter_changeroffer_maxamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeroffer',
            name='bannerName',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название оффера'),
        ),
    ]
