# Generated by Django 4.2 on 2023-04-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0003_alter_changeroffer_bannername'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerbankaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='db_model.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='currency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='db_model.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
