# Generated by Django 4.2 on 2023-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0004_changerbankaccount_currency_userbankaccount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMongolianBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Все банки',
            },
        ),
    ]
