# Generated by Django 4.2 on 2023-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0005_allmongolianbanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerbankaccount',
            name='comments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='comments',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
