# Generated by Django 4.2 on 2023-04-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0006_changerbankaccount_comments_userbankaccount_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='changerProofType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='userProofType',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
