# Generated by Django 4.2 on 2023-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0008_alter_transaction_changerproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='changerAcceptDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='changerSendMoneyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='userAcceptDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='userSendMoneyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
