# Generated by Django 4.2 on 2023-04-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0009_alter_transaction_changeracceptdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isCompleted',
            field=models.BooleanField(default=True),
        ),
    ]
