# Generated by Django 4.2 on 2023-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0010_transaction_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
