# Generated by Django 4.2 on 2023-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0011_alter_transaction_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='claims',
            field=models.BooleanField(default=False),
        ),
    ]
